### ISSUE TITLE
Error processing CanRCM4_Cor_WFDEI-GEM-CaPA data

### ISSUE THREAD

**Issue by KevinShook** [ShervanGharari/EASYMORE#40]
Processing dataset r10i2p1r4 results in an error for the wind variable. All other variables are OK.
I've attached the error file as well as the easymore Python file and the output file.
[easymore_wind_files.zip](https://github.com/ShervanGharari/EASYMORE/files/10952051/easymore_wind_files.zip)

All other variables are OK.
There does not seem to be any issue with the `datatool` as running it did not produce errors.

A

**Comment by ShervanGharari** [comment]
Interesting and thank you for raising this.
From the error file, it seems that it is coming from the `xarray`. It seems the wind file has an identical time index associated with it (as if a date or time is repeated). Can you perhaps drop all the variables from the nc file, to reduce the size, and attach it here as well? I need to check the time variable first.

**Comment by KevinShook** [comment]
Will do. I suspected that there is something wrong with the file.

**Comment by KevinShook** [comment]
Here's the time values exported to a text file and compressed

[time.txt.zip](https://github.com/ShervanGharari/EASYMORE/files/10952202/time.txt.zip)

**Comment by ShervanGharari** [comment]
it seems the time index (or values in time) are not unique as expected.
here is the snapshot from line 3391 onward:
```
10167.0	10167.0
10170.0	10170.0
10173.0	10173.0
10200.0	10200.0
10203.0	10203.0
10206.0	10206.0
10209.0	10209.0
10212.0	10212.0
10215.0	10215.0
10218.0	10218.0
10221.0	10221.0
10200.0	10200.0
10203.0	10203.0
10206.0	10206.0
```
as you can see 10200 is repeated. I suspect this is due to some issues with adding 29 February to the original dataset (which has a 365 calendar). In the case of line 3391, I suspect this is the 29th of February for the year 1980.
As this issue is not related to `easymore`, if there is no other concern I'll close this issue. I'll come back to you on the original data in another platform.

**Comment by KevinShook** [comment]
Thanks!
